In [1]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re

# Funções

In [2]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [3]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

## Testes em 3 ordens

In [4]:
input = np.asmatrix(np.loadtxt('dados.txt', dtype='f', delimiter=','))
x, y = (input[:,0].T,input[:,1].T)
print(x, "\n", y)

[[  5.1  20.8  39.5  59.3  79.4 100.2 119.9 139.3 161.7 180.5]] 
 [[  5.  20.  40.  60.  80. 100. 120. 140. 160. 180.]]


In [5]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))

[[0.9962751]] [[0.2673644]]
[[  5.  20.  40.  60.  80. 100. 120. 140. 160. 180.]] 
 [[  5.34836732  20.98988571  39.62023083  59.34647704  79.37160882
  100.09412633 119.72075035 139.0484888  161.36504495 180.09501986]]
2.220814273849708


In [6]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))

[[-0.00014038]] [[1.02213734]] [[-0.46916996]]
[[  5.  20.  40.  60.  80. 100. 120. 140. 160. 180.]] 
 [[  4.74007901  20.7305505   39.68622188  59.64991696  79.80350932
  100.53953432 120.06694648 139.19049777 161.13984765 179.45289612]]
1.8467091457336138


In [7]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))

[[6.7778682e-07]] [[-0.00032913]] [[1.03584413]] [[-0.65783167]]
[[  5.  20.  40.  60.  80. 100. 120. 140. 160. 180.]] 
 [[  4.61650262  20.75143111  39.78626214  59.75168806  79.85253208
  100.51115465 119.9766291  139.08079401 161.09814794 179.5748583 ]]
1.8259922543403124
